---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-ilab06
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-ilab06 
  name: test-ilab06
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi